### ISSUE TITLE
Rotosolve failed in `disable_eager_execution`

### ISSUE THREAD

**Issue by we-taper** [tensorflow/quantum#412]
Rotosolve currently contains code that isn't supported in `disable_eager_execution` mode:

https://github.com/tensorflow/quantum/blob/f9a015a5664dce88ca99f6de85eaf5376ae0cf3a/tensorflow_quantum/python/optimizers/rotosolve_minimizer.py#L236

To reproduce:

```python
# %%
import tensorflow_quantum as tfq
import tensorflow as tf
import numpy as np

# %%
tf.compat.v1.disable_eager_execution()

# %%
n = 10  # Number of sinusoids
coefficient = tf.random.uniform(shape=[n])
min_value = -tf.math.reduce_sum(tf.abs(coefficient))
func = lambda x: tf.math.reduce_sum(tf.sin(x) * coefficient)
# Optimize the function with rotosolve, start with random parameters
result = tfq.optimizers.rotosolve_minimize(func, np.random.random(n))
print(result.converged)
print(result.objective_value)
```

Gives error message:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-0f3f779174a0>", line 6, in <module>
    result = tfq.optimizers.rotosolve_minimize(func, np.random.random(n))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_quantum/python/optimizers/rotosolve_minimizer.py", line 263, in minimize
    parallel_iterations=1)[0]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2499, in while_loop_v2
    return_same_structure=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2696, in while_loop
    back_prop=back_prop)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/while_v2.py", line 151, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/while_v2.py", line 130, in wrapped_cond
    pred = cond(*_pack_sequence_as(orig_loop_vars, args))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_quantum/python/optimizers/rotosolve_minimizer.py", line 236, in _cond
    return (state.num_iterations < max_iterations) \
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 877, in __bool__
    self._disallow_bool_casting()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 490, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 479, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

```

**Comment by MichaelBroughton** [comment]
This appears to be an issue with using the v1 api (which was around and deprecated before TFQ came out and likely a will not fix on our end). If you would like to disable running functions eagerly you can do something like:

```python3
tf.config.run_functions_eagerly(False)
```

Which still appears to work with this snippet.

**Comment by lockwo** [comment]
Any updates on this issue @we-taper or can it be closed?

**Comment by we-taper** [comment]
Yes, thanks for the comments.
