### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by lockwo** [tensorflow/quantum#630]
There seems to be some issue installing TFQ that is eliminated when installing TFQ nightly. I have checked this on two different brand new environments. First, I booted up a simple cloud cpu instance. Following the install instructions, I install TF 2.5.1 and install TFQ. However, I see the following error when I try to import TFQ: 
```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_quantum/core/ops/load_module.py", line 42, in load_module
    return load_library.load_op_library(path)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/dist-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: undefined symbol: _ZN10tensorflow15OpKernelContext5inputEN4absl14lts_2020_02_2511string_viewEPPKNS_6TensorE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_quantum/__init__.py", line 18, in <module>
    from tensorflow_quantum.core import (append_circuit, get_expectation_op,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_quantum/core/__init__.py", line 17, in <module>
    from tensorflow_quantum.core.ops import (get_expectation_op,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_quantum/core/ops/__init__.py", line 18, in <module>
    from tensorflow_quantum.core.ops.circuit_execution_ops import (
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_quantum/core/ops/circuit_execution_ops.py", line 20, in <module>
    from tensorflow_quantum.core.ops import (cirq_ops, tfq_simulate_ops,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_quantum/core/ops/tfq_simulate_ops.py", line 19, in <module>
    SIM_OP_MODULE = load_module("_tfq_simulate_ops.so")
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_quantum/core/ops/load_module.py", line 46, in load_module
    return load_library.load_op_library(path)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/lib/python3/dist-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: cannot open shared object file: No such file or directory
```

After seeing this error, I install TFQ-nightly and the problem is resolved (I can import and use TFQ exactly as expected). I repeated this experiment on my local machine with a brand new conda environment and after installing TF 2.5.1 and TFQ I see an error (albeit a different one): 

```
Traceback (most recent call last):
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/core/ops/load_module.py", line 42, in load_module
    return load_library.load_op_library(path)
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: undefined symbol: _ZN10tensorflow15OpKernelContext5inputEN4absl14lts_2020_02_2511string_viewEPPKNS_6TensorE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/__init__.py", line 18, in <module>
    from tensorflow_quantum.core import (append_circuit, get_expectation_op,
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/core/__init__.py", line 17, in <module>
    from tensorflow_quantum.core.ops import (get_expectation_op,
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/core/ops/__init__.py", line 18, in <module>
    from tensorflow_quantum.core.ops.circuit_execution_ops import (
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/core/ops/circuit_execution_ops.py", line 20, in <module>
    from tensorflow_quantum.core.ops import (cirq_ops, tfq_simulate_ops,
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/core/ops/tfq_simulate_ops.py", line 19, in <module>
    SIM_OP_MODULE = load_module("_tfq_simulate_ops.so")
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/core/ops/load_module.py", line 46, in load_module
    return load_library.load_op_library(path)
  File "/home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/owenl/miniconda3/envs/tfq_install_test/lib/python3.8/site-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: undefined symbol: _ZN10tensorflow15OpKernelContext5inputEN4absl14lts_2020_02_2511string_viewEPPKNS_6TensorE
```

After installing TFQ nightly, all works as expected.

Given that this installation error occurs on multiple machines that have brand new (no other packages installed) environments and are resolved with installing TFQ nightly, I believe there may be some error in the current version of TFQ (that is solved in the nightly one). I do not know what the problem is and it is possible I am doing something wrong, so feel free to check with a new environment of your own. 

Note that the exact commands run were: pip3 install tensorflow==2.5.1 and pip3 install tensorflow-quantum and testing via import tensorflow_quantum.

**Comment by zaqqwerty** [comment]
The problem is that the last release of TFQ still depends on tensorflow==2.4.1, see the requirements.txt in [the release tagged source code](https://github.com/tensorflow/quantum/tree/v0.5.1).  TF 2.5.1 is only supported in the nightly build.

**Comment by lockwo** [comment]
Oh I see. I was going off the install from the docs. Maybe that should be adjusted to say 2.4.1 instead of 2.5.1? https://www.tensorflow.org/quantum/install
