### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by SurferZergy** [tensorflow/quantum#701]
Hi, a pip install tensorflow-quantum take a very long time (likely due to things like INFO: pip is looking at multiple versions of mpmath to determine which version is compatible with other requirements. This could take a while.) and result is it fails with error:
`ERROR: Exception:
Traceback (most recent call last):
  File "/home/james/miniconda3/envs/gitdev/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/james/miniconda3/envs/gitdev/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/james/miniconda3/envs/gitdev/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/home/james/miniconda3/envs/gitdev/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/james/miniconda3/envs/gitdev/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/james/miniconda3/envs/gitdev/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 383, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
`

I've tried using tensorflow 2.4.1 with tensorflow-quantum 0.5.0 as mentioned in https://www.tensorflow.org/quantum/install, as well as tensorflow 2.7.0 and tensorflow-quantum 0.6.0 mentioned in https://github.com/tensorflow/quantum/releases.

**Comment by lockwo** [comment]
What version of pip are you using? I just tested with `pip 22.2` and it installed about as quickly as expected (<1 min). https://github.com/tensorflow/quantum/issues/696 seems to indicate this might be an issue with pip.

**Comment by SurferZergy** [comment]
ah updated fixed
