### ISSUE TITLE
problems when run a project

### ISSUE THREAD

**Issue by jasonpoonreal** [tensorflow/quantum#812]
/home/jasonpoon/anaconda3/envs/tfq/bin/python /home/jasonpoon/PycharmProjects/pythonProject4/1.py 
Traceback (most recent call last):
  File "/home/jasonpoon/PycharmProjects/pythonProject4/1.py", line 4, in <module>
    import tensorflow_quantum as tfq
  File "/home/jasonpoon/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow_quantum/__init__.py", line 18, in <module>
    from tensorflow_quantum.core import (append_circuit, get_expectation_op,
  File "/home/jasonpoon/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow_quantum/core/__init__.py", line 17, in <module>
    from tensorflow_quantum.core.ops import (get_expectation_op,
  File "/home/jasonpoon/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow_quantum/core/ops/__init__.py", line 18, in <module>
    from tensorflow_quantum.core.ops.circuit_execution_ops import (
  File "/home/jasonpoon/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow_quantum/core/ops/circuit_execution_ops.py", line 20, in <module>
    from tensorflow_quantum.core.ops import (cirq_ops, tfq_simulate_ops,
  File "/home/jasonpoon/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow_quantum/core/ops/tfq_simulate_ops.py", line 17, in <module>
    from tensorflow_quantum.core.ops.load_module import load_module
  File "/home/jasonpoon/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow_quantum/core/ops/load_module.py", line 20, in <module>
    from tensorflow.python.framework import load_library
ModuleNotFoundError: No module named 'tensorflow.python.framework'

Process finished with exit code 1
![image](https://github.com/user-attachments/assets/bcefb85b-5b27-4528-a6b3-7c1ac7ae7bf2)

**Comment by mhucka** [comment]
Thank you for taking the time to file a report. Unfortunately, there is not enough information here to start answering. We need to know at least how you installed TensorFlow and TensorFlow Quantum, which versions, and on what platforms. Please refer to the installation instructions at https://www.tensorflow.org/quantum/install and let us know which approach you took.
